import { useState } from "react";
import { withBase } from "@/lib/paths";
import { getActivePlaylist, getTrack, nextTrack, prevTrack, setVolume, toggleMuted, togglePlaying, useMusicState } from "@/lib/music/store";
const fmt = (s: number) => `${Math.floor(s / 60)}:${Math.floor(s % 60).toString().padStart(2, "0")}`;
export default function MusicHeroPlayer() {
  const state = useMusicState(); const track = getTrack(); const playlist = getActivePlaylist(); const [tab, setTab] = useState<"info" | "lyrics">("info");
  if (!track) return <section className="music-hero-player music-player-empty"><h2>播放列表为空</h2></section>;
  const duration = state.duration || (track.durationMs ?? 0) / 1000; const volume = state.volume ?? .8; const icon = state.muted || volume === 0 ? "🔇" : volume < .45 ? "🔉" : "🔊";
  return <section className="music-hero-player" aria-label="音乐播放器"><div className="hero-playing-side"><div className="hero-disc-art" data-playing={state.playing}><div className="hero-disc" aria-hidden="true"><i>WL</i></div>{track.artworkUrl ? <img src={withBase(track.artworkUrl)} alt={`${track.title} 封面`} /> : <span className="hero-art-fallback">✦</span>}</div><p className="hero-kicker">{playlist?.title ?? "MUSIC"}</p><h2>{track.title}</h2><p className="hero-byline">{track.artist}{track.album ? ` · ${track.album}` : ""}</p><div className="hero-progress" aria-label={`播放进度 ${fmt(state.currentTime)} / ${fmt(duration)}`}><i style={{ width: `${Math.round(state.progress * 100)}%` }} /></div><div className="hero-times"><span>{fmt(state.currentTime)}</span><span>{duration ? fmt(duration) : "--:--"}</span></div><div className="hero-controls"><button type="button" onClick={prevTrack} aria-label="上一首">⏮</button><button type="button" className="hero-play" onClick={togglePlaying} disabled={!track.previewUrl} aria-label={track.previewUrl ? (state.playing ? "暂停试听" : "播放试听") : "当前曲目不可试听"}>{state.playing ? "Ⅱ" : "▶"}</button><button type="button" onClick={() => nextTrack()} aria-label="下一首">⏭</button><label className="hero-volume"><button type="button" onClick={toggleMuted} aria-label={state.muted ? "恢复声音" : "静音"}>{icon}</button><input type="range" min="0" max="1" step=".01" value={volume} onChange={e => setVolume(Number(e.target.value))} aria-label="音量" /></label></div>{!track.previewUrl && <small className="hero-preview-note">当前曲目不可试听</small>}{state.error && <p className="music-player-error" role="status">{state.error}</p>}</div><div className="hero-context-side"><div className="music-tabs" role="tablist" aria-label="曲目内容"><button type="button" role="tab" aria-selected={tab === "info"} onClick={() => setTab("info")}>信息</button><button type="button" role="tab" aria-selected={tab === "lyrics"} onClick={() => setTab("lyrics")}>歌词</button></div>{tab === "info" ? <div className="hero-info-panel" role="tabpanel"><dl><div><dt>艺术家</dt><dd>{track.artist}</dd></div><div><dt>专辑</dt><dd>{track.album ?? "—"}</dd></div><div><dt>播放列表</dt><dd>{playlist?.title ?? "—"}</dd></div><div><dt>时长</dt><dd>{duration ? fmt(duration) : "—"}</dd></div></dl>{track.thoughts && <p className="hero-thoughts">{track.thoughts}</p>}</div> : <div className="hero-lyrics-panel" role="tabpanel"><h3>暂无歌词</h3><p>{track.thoughts ?? "当前档案没有可展示的歌词内容。"}</p></div>}</div></section>;
}
