import { useState } from "react";
import { withBase } from "@/lib/paths";
import { getActivePlaylist, getTrack, nextTrack, prevTrack, toggleMuted, togglePlaying, useMusicState } from "@/lib/music/store";

const fmt = (seconds: number) => `${Math.floor(seconds / 60)}:${Math.floor(seconds % 60).toString().padStart(2, "0")}`;
export default function MusicHeroPlayer() {
  const state = useMusicState(); const track = getTrack(); const playlist = getActivePlaylist(); const [tab, setTab] = useState<"info" | "lyrics">("info");
  if (!track) return <section className="music-hero-player music-player-empty"><h2>播放列表为空</h2><p>暂无可供选择的本地音乐内容。</p></section>;
  const duration = state.duration || track.durationMs ? (state.duration || (track.durationMs ?? 0) / 1000) : 0;
  return <section className="music-hero-player" aria-label="音乐播放器"><div className="hero-playing-side"><div className="hero-disc-art" data-playing={state.playing}><div className="hero-disc" aria-hidden="true"><i>WL</i></div>{track.artworkUrl ? <img src={withBase(track.artworkUrl)} alt={`${track.title} 封面`} /> : <span className="hero-art-fallback">♫</span>}</div><p className="hero-kicker">{state.playing ? "正在试听" : track.previewUrl ? "准备试听" : "试听未配置"}</p><h2>{track.title}</h2><p className="hero-byline">{track.artist}{track.album ? ` · ${track.album}` : ""}</p><div className="hero-progress" aria-label={`播放进度 ${fmt(state.currentTime)} / ${fmt(duration)}`}><i style={{ width: `${Math.round(state.progress * 100)}%` }} /></div><div className="hero-times"><span>{fmt(state.currentTime)}</span><span>{duration ? fmt(duration) : "--:--"}</span></div><div className="hero-controls"><button type="button" onClick={prevTrack} aria-label="上一首">‹‹</button><button type="button" className="hero-play" onClick={togglePlaying} disabled={!track.previewUrl} aria-label={state.playing ? "暂停试听" : track.previewUrl ? "播放试听" : "暂无试听"}>{state.playing ? "暂停" : track.previewUrl ? "播放" : "暂无试听"}</button><button type="button" onClick={() => nextTrack()} aria-label="下一首">››</button><button type="button" onClick={toggleMuted} aria-label={state.muted ? "取消静音" : "静音"}>{state.muted ? "静音" : "音量"}</button></div>{state.error && <p className="music-player-error" role="status">{state.error}</p>}{track.appleMusicUrl && <a className="hero-apple-link" href={track.appleMusicUrl} target="_blank" rel="noreferrer noopener">在 Apple Music 打开 ↗</a>}</div>
  <div className="hero-context-side"><div className="music-tabs" role="tablist" aria-label="曲目内容"><button type="button" role="tab" aria-selected={tab === "info"} onClick={() => setTab("info")}>信息</button><button type="button" role="tab" aria-selected={tab === "lyrics"} onClick={() => setTab("lyrics")}>歌词</button></div>{tab === "info" ? <div className="hero-info-panel" role="tabpanel"><dl><div><dt>艺术家</dt><dd>{track.artist}</dd></div><div><dt>专辑</dt><dd>{track.album ?? "—"}</dd></div><div><dt>播放列表</dt><dd>{playlist?.title ?? "—"}</dd></div><div><dt>发行日期</dt><dd>{track.releaseDate ?? "—"}</dd></div><div><dt>流派</dt><dd>{track.genres.length ? track.genres.join(" · ") : "—"}</dd></div><div><dt>时长</dt><dd>{duration ? fmt(duration) : "—"}</dd></div></dl>{track.thoughts && <p className="hero-thoughts">{track.thoughts}</p>}</div> : <div className="hero-lyrics-panel" role="tabpanel"><h3>暂无歌词</h3>{track.thoughts ? <p><span>氛围片段</span>{track.thoughts}</p> : <p>当前档案没有可展示的歌词内容。</p>}</div>}</div></section>;
}
