import { useEffect, useRef, useState } from "react";
import { animate, motion, useMotionValue, useMotionValueEvent, useSpring, useTransform } from "motion/react";
import { withBase } from "@/lib/paths";
import { playTrack, selectTrack } from "@/lib/music/store";
import type { MusicArchiveTrack, MusicPlaylist } from "@/lib/apple-music/types";

const fmt = (ms?: number) => ms ? `${Math.floor(ms / 60000)}:${Math.floor((ms % 60000) / 1000).toString().padStart(2, "0")}` : "--:--";
const circular = (index: number, p: number, count: number) => ((index - p + count / 2) % count + count) % count - count / 2;
const nearest = (value: number, count: number) => ((Math.round(value) % count) + count) % count;
type Progress = ReturnType<typeof useMotionValue<number>>;

function CrystalBlade({ track, index, count, progress, choose }: { track: MusicArchiveTrack; index: number; count: number; progress: Progress; choose: (index: number) => void }) {
  const offset = useTransform(progress, p => circular(index, p, count));
  const angle = useTransform(offset, o => o * .62);
  const x = useTransform(angle, a => Math.sin(a) * 300);
  const z = useTransform(angle, a => Math.cos(a) * 430 - 430);
  const y = useTransform(angle, a => (1 - Math.cos(a)) * 72);
  const highlight = useTransform(angle, a => `${50 + Math.max(-35, Math.min(35, a * 54))}%`);
  return <motion.button type="button" className="crystal-blade" style={{ x, y, z, rotateY: useTransform(angle, a => -a * 57.3), rotateZ: useTransform(offset, o => o * 2), scale: useTransform(offset, o => Math.max(.57, 1 - Math.abs(o) * .11)), opacity: useTransform(offset, o => Math.max(.12, 1 - Math.abs(o) * .19)), filter: useTransform(offset, o => `saturate(${Math.max(.45, 1.2 - Math.abs(o) * .16)}) blur(${Math.max(0, Math.abs(o) - 2) * .7}px)`), zIndex: useTransform(offset, o => 100 - Math.round(Math.abs(o) * 10)), "--highlight-x": highlight } as never} onClick={() => choose(index)} aria-label={`选择 ${track.title}`}><span className="crystal-edge" /><span className="crystal-art">{track.artworkUrl ? <img src={withBase(track.artworkUrl)} alt="" /> : "✦"}</span><span className="crystal-copy"><b>{track.title}</b><small>{track.artist}</small></span></motion.button>;
}

export default function TrackWheelDialog({ playlist, onClose }: { playlist: MusicPlaylist; onClose: () => void }) {
  const tracks = playlist.tracks; const progress = useMotionValue(0); const smooth = useSpring(progress, { stiffness: 210, damping: 24, mass: .8 }); const [selected, setSelected] = useState(0); const samples = useRef<{ x: number; p: number; t: number }[]>([]); const close = useRef<HTMLButtonElement>(null);
  const moveTo = (target: number, velocity = 0) => { const direction = Math.round(target - progress.get()); const normalized = direction > tracks.length / 2 ? target - tracks.length : direction < -tracks.length / 2 ? target + tracks.length : target; setSelected(nearest(normalized, tracks.length)); animate(progress, normalized, { type: "spring", stiffness: 205, damping: 23, mass: .78, velocity }); };
  const snap = (velocity = 0) => { const projected = progress.get() + velocity * .22; const target = Math.round(projected); moveTo(target, velocity); setSelected(nearest(target, tracks.length)); };
  useMotionValueEvent(progress, "change", value => setSelected(nearest(value, tracks.length)));
  useEffect(() => { const old = document.body.style.overflow; document.body.style.overflow = "hidden"; close.current?.focus(); const key = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); if (e.key === "ArrowLeft") moveTo(Math.round(progress.get()) - 1); if (e.key === "ArrowRight") moveTo(Math.round(progress.get()) + 1); }; window.addEventListener("keydown", key); return () => { document.body.style.overflow = old; window.removeEventListener("keydown", key); }; }, [onClose]);
  const play = () => { const track = tracks[selected]; selectTrack(playlist.id, track.id); if (track.previewUrl) playTrack(track.id, playlist.id); onClose(); };
  return <motion.div className="track-wheel-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onPointerDown={e => { if (e.target === e.currentTarget) onClose(); }}><motion.section className="track-wheel-dialog" role="dialog" aria-modal="true" aria-label={`${playlist.title} 曲目水晶轮盘`} initial={{ opacity: 0, scale: .94, y: 18 }} animate={{ opacity: 1, scale: 1, y: 0 }} transition={{ type: "spring", stiffness: 230, damping: 25 }}><header><span>{playlist.title}</span><button ref={close} type="button" onClick={onClose} aria-label="关闭曲目滚轮">×</button></header><motion.div layoutId={`playlist-cover-${playlist.id}`} className="track-wheel-cover">{playlist.cover ? <img src={withBase(playlist.cover)} alt="" /> : "✦"}</motion.div><div className="track-wheel" onWheel={e => { e.preventDefault(); moveTo(progress.get() + e.deltaY / 360, -e.deltaY / 100); }} onPointerDown={e => { const p = progress.get(); samples.current = [{ x: e.clientX, p, t: performance.now() }]; e.currentTarget.setPointerCapture(e.pointerId); }} onPointerMove={e => { if (!e.currentTarget.hasPointerCapture(e.pointerId)) return; const first = samples.current[0]; const p = first.p - (e.clientX - first.x) / 145; progress.set(p); samples.current.push({ x: e.clientX, p, t: performance.now() }); if (samples.current.length > 5) samples.current.shift(); }} onPointerUp={e => { const first = samples.current[0]; const last = samples.current.at(-1); const velocity = first && last ? (last.p - first.p) / Math.max(1, last.t - first.t) * 1000 : 0; snap(velocity); e.currentTarget.releasePointerCapture(e.pointerId); }}><div className="track-wheel-stage">{tracks.map((track, index) => <CrystalBlade key={track.id} track={track} index={index} count={tracks.length} progress={smooth} choose={i => moveTo(i)} />)}</div><div className="track-wheel-selected"><span>{String(selected + 1).padStart(2, "0")} / {String(tracks.length).padStart(2, "0")}</span><h2>{tracks[selected]?.title}</h2><p>{tracks[selected]?.artist} · {fmt(tracks[selected]?.durationMs)}</p><button className="track-wheel-play" type="button" disabled={!tracks[selected]?.previewUrl} onClick={play} aria-label={tracks[selected]?.previewUrl ? `播放 ${tracks[selected]?.title}` : "当前曲目不可试听"}>▶</button>{!tracks[selected]?.previewUrl && <small>不可试听</small>}</div><div className="track-wheel-controls"><button type="button" onClick={() => moveTo(Math.round(progress.get()) - 1)} aria-label="上一首">←</button><button type="button" onClick={() => moveTo(Math.round(progress.get()) + 1)} aria-label="下一首">→</button></div></div></motion.section></motion.div>;
}
