import { useEffect, useMemo, useState } from "react";
import MotionList from "@/components/motion/MotionList";
import FilterSelect from "@/components/ui/FilterSelect";

export interface AnimeFeedItem { id:string; title:string; titleJP?:string; status:string; statusLabel:string; score?:number; episodes?:number; currentEpisode?:number; cover?:string; tags:string[]; thoughts?:string; date:string; href:string; }
interface Props { items:AnimeFeedItem[]; statuses:{value:string;label:string;count:number}[]; tags:{value:string;count:number}[]; }
export default function AnimeFeed({items,statuses,tags}:Props) {
 const [status,setStatus]=useState("all"),[tag,setTag]=useState("all"),[raw,setRaw]=useState(""),[query,setQuery]=useState(""),[sort,setSort]=useState<"newest"|"oldest">("newest");
 useEffect(()=>{const t=window.setTimeout(()=>setQuery(raw.trim().toLowerCase()),100);return()=>clearTimeout(t)},[raw]);
 const shown=useMemo(()=>items.filter(x=>(status==="all"||x.status===status)&&(tag==="all"||x.tags.includes(tag))&&(!query||`${x.title} ${x.titleJP??""} ${x.thoughts??""} ${x.tags.join(" ")}`.toLowerCase().includes(query))).sort((a,b)=>sort==="newest"?+new Date(b.date)-+new Date(a.date):+new Date(a.date)-+new Date(b.date)),[items,status,tag,query,sort]);
 return <div data-motion-managed="react" data-motion-scene="anime"><div className="filter-panel mb-8 flex flex-col gap-4 p-4 sm:p-5"><div className="filter-bar"><div className="filter-group"><button className="filter-chip" data-active={status==="all"} onClick={()=>setStatus("all")}>全部 <span className="chip-count">{items.length}</span></button>{statuses.map(s=><button key={s.value} className="filter-chip" data-active={status===s.value} onClick={()=>setStatus(s.value)}>{s.label} <span className="chip-count">{s.count}</span></button>)}</div></div><div className="filter-bar"><div className="filter-group"><button className="filter-chip" data-active={tag==="all"} onClick={()=>setTag("all")}>全部</button>{tags.map(t=><button key={t.value} className="filter-chip" data-active={tag===t.value} onClick={()=>setTag(t.value)}>{t.value} <span className="chip-count">{t.count}</span></button>)}</div></div><div className="filter-bar"><label className="filter-search"><span>⌕</span><input value={raw} onChange={e=>setRaw(e.target.value)} type="search" placeholder="搜索标题 / 短评 / 标签…" /></label><FilterSelect value={sort} onChange={setSort} options={[{ value: "newest", label: "最新" }, { value: "oldest", label: "最早" }]} /><span className="filter-count-line">{shown.length} 部</span></div></div>{shown.length===0?<div className="filter-empty glass">没有匹配的番剧</div>:<MotionList id="anime-feed" scene="anime" items={shown} getKey={x=>x.id} className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3" renderItem={x=><a href={x.href} className="anime-card glass-card clickable group relative flex flex-col gap-3 p-4"><div className="relative aspect-[16/10] overflow-hidden rounded-xl border border-[var(--ia-line)]">{x.cover?<img src={x.cover} alt="" className="size-full object-cover"/>:<div className="grid size-full place-items-center bg-[var(--ia-panel)] text-4xl">{x.title[0]}</div>}<span className="absolute left-2 top-2 rounded bg-black/50 px-2 py-1 mono text-[10px]">{x.statusLabel}</span>{typeof x.score==="number"&&<span className="absolute right-2 top-2 rounded bg-black/50 px-2 py-1 mono text-[10px]">★ {x.score.toFixed(1)}</span>}</div><div><h3 className="text-sm font-semibold text-[var(--ia-ink)]">{x.title}</h3>{x.titleJP&&<p className="mono text-[11px] text-[var(--ia-mist)]">{x.titleJP}</p>}</div>{x.thoughts&&<p className="line-clamp-2 text-xs text-[var(--ia-mist)]">{x.thoughts}</p>}<div className="mt-auto flex justify-between mono text-[11px] text-[var(--ia-mist)]"><span>{x.currentEpisode&&x.episodes?`EP ${x.currentEpisode}/${x.episodes}`:""}</span><span>{x.tags.slice(0,2).join(" · ")}</span></div></a>}/>}</div>
}
