import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, LayoutGroup, motion, useReducedMotion } from "motion/react";
import { layoutSpring, motionTokens } from "@/lib/motion/presets";

export interface TimelineMotionItem {
  id: string; type: string; typeLabel: string; title: string; description?: string;
  date: string; href?: string; tags: string[]; color: string;
}
interface Props { items: TimelineMotionItem[]; types: { type: string; label: string; count: number; color: string }[]; }
const dateText = (value: string) => new Intl.DateTimeFormat("zh-CN", { year: "numeric", month: "short", day: "numeric" }).format(new Date(value));

/** Timeline semantic island: the axis owns its narrative; cards own only their local enter/exit. */
export default function TimelineMotion({ items, types }: Props) {
  const [type, setType] = useState("all"); const [rawQuery, setRawQuery] = useState(""); const [query, setQuery] = useState(""); const [sort, setSort] = useState<"newest" | "oldest">("newest");
  const reduced = useReducedMotion() ?? false;
  useEffect(() => { const timer = window.setTimeout(() => setQuery(rawQuery.trim().toLowerCase()), 100); return () => window.clearTimeout(timer); }, [rawQuery]);
  const visible = useMemo(() => items.filter((item) => (type === "all" || item.type === type) && (!query || `${item.title} ${item.description ?? ""} ${item.tags.join(" ")} ${item.typeLabel}`.toLowerCase().includes(query))).sort((a,b) => sort === "newest" ? +new Date(b.date) - +new Date(a.date) : +new Date(a.date) - +new Date(b.date)), [items, type, query, sort]);
  const groups = useMemo(() => { const grouped = new Map<number, TimelineMotionItem[]>(); visible.forEach((item) => { const year = new Date(item.date).getFullYear(); grouped.set(year, [...(grouped.get(year) ?? []), item]); }); return [...grouped.entries()].sort(([a],[b]) => sort === "newest" ? b-a : a-b); }, [visible, sort]);
  return <div data-motion-managed="react" data-motion-scene="timeline">
    <div className="filter-panel mb-8 flex flex-col gap-4 p-4 sm:p-5"><div className="filter-bar"><div className="filter-group" role="group" aria-label="按类型筛选"><button type="button" className="filter-chip" data-active={type === "all"} onClick={() => setType("all")}>全部 <span className="chip-count">{items.length}</span></button>{types.map((item) => <button key={item.type} type="button" className="filter-chip" data-active={type === item.type} style={{ "--acc": item.color } as React.CSSProperties} onClick={() => setType(item.type)}><span className="chip-dot" />{item.label} <span className="chip-count">{item.count}</span></button>)}</div></div><div className="filter-bar"><label className="filter-search"><span aria-hidden>⌕</span><input type="search" value={rawQuery} onChange={(e) => setRawQuery(e.target.value)} placeholder="在标题、摘要与标签中检索…" aria-label="搜索时间线记录" /></label><select className="filter-sort" value={sort} onChange={(e) => setSort(e.target.value as "newest" | "oldest")} aria-label="排序方式"><option value="newest">最新优先</option><option value="oldest">最早优先</option></select><span className="filter-count-line">{visible.length} records</span></div></div>
    <AnimatePresence initial={false}>{visible.length === 0 && <motion.div className="filter-empty glass" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>没有匹配的存档记录</motion.div>}</AnimatePresence>
    <LayoutGroup id="timeline-flow"><motion.div layout transition={reduced ? {duration:.12} : layoutSpring} className="flex flex-col gap-10"><AnimatePresence mode="popLayout" initial={!reduced}>{groups.map(([year, entries], groupIndex) => <motion.section key={year} layout="position" className="timeline-year" initial={reduced ? {opacity:0} : {opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:.2}}><div className="mb-4 flex items-center gap-3"><h2 className="font-serif text-3xl font-bold text-[var(--ia-ink)]">{year}</h2><span className="mono text-[11px] text-[var(--ia-mist)]">{entries.length} records</span><span className="h-px flex-1 bg-[var(--ia-line)]" /></div><div className="relative pl-6"><motion.span className="timeline-line absolute bottom-2 left-[7px] top-2 w-px bg-gradient-to-b from-[var(--ia-line-strong)] via-[var(--ia-line)] to-transparent" style={{transformOrigin:"top"}} initial={reduced ? {opacity:1} : {scaleY:0,opacity:.3}} animate={{scaleY:1,opacity:1}} transition={{duration:reduced ? .12 : .52, delay:reduced ? 0 : Math.min(groupIndex, 3) * .04}} /><motion.ul layout transition={reduced ? {duration:.12} : layoutSpring} className="flex flex-col gap-5">{entries.map((item, index) => <motion.li layout="position" key={`${item.type}:${item.id}`} className="timeline-record relative" initial={reduced ? {opacity:0} : {opacity:0,y:12,scale:.99}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:7,scale:.97}} transition={reduced ? {duration:.12} : {layout:layoutSpring, opacity:{duration:.2}, y:{type:"spring",stiffness:175,damping:23,mass:.82}, delay:Math.min(index,motionTokens.maxStaggeredItems)*motionTokens.desktopStagger}}><motion.span className="timeline-node absolute -left-[21px] top-2 grid size-3.5 place-items-center rounded-full ring-2 ring-[var(--ia-bg)]" style={{background:item.color,boxShadow:`0 0 10px ${item.color}`}} initial={reduced?{opacity:1}:{opacity:0,scale:.25}} animate={{opacity:1,scale:1}} transition={{duration:.24,delay:reduced?0:Math.min(index,6)*.035}} />{item.href ? <a href={item.href} className="glass-card clickable group block rounded-xl p-4"><Card item={item}/></a> : <div className="glass-card block rounded-xl p-4"><Card item={item}/></div>}</motion.li>)}</motion.ul></div></motion.section>)}</AnimatePresence></motion.div></LayoutGroup></div>;
}
function Card({ item }: {item: TimelineMotionItem}) { return <><div className="flex items-center gap-2"><span className="inline-flex items-center gap-1 rounded-md px-2 py-0.5 mono text-[10px] uppercase tracking-wider" style={{color:item.color,border:`1px solid color-mix(in srgb, ${item.color} 40%, transparent)`}}>{item.typeLabel}</span><time className="ml-auto mono text-[11px] text-[var(--ia-mist)]">{dateText(item.date)}</time></div><h3 className="mt-2 text-[15px] font-semibold text-[var(--ia-ink)]">{item.title}</h3>{item.description && <p className="mt-1 line-clamp-2 text-sm leading-relaxed text-[var(--ia-mist)]">{item.description}</p>}{item.tags.length > 0 && <div className="mt-2 flex flex-wrap gap-1">{item.tags.slice(0,5).map((tag) => <span className="tag-chip" key={tag}>{tag}</span>)}</div>}</>; }
