import { useEffect, useRef, useState } from "react";
import { animate, motion, useMotionValue, useMotionValueEvent, useTransform } from "motion/react";

const tracks = ["NIGHT SIGNAL", "METEOR CACHE", "GLASS RAIN", "EL PSY LOOP", "LOW ORBIT", "AFTERIMAGE", "SLOW BUILD", "BLUE HOUR", "QUIET ARRAY", "DIVERGENCE"];
const count = tracks.length; const step = Math.PI / 5.8; const radiusX = 420; const radiusZ = 510; const verticalDrop = 96; const pixelsPerItem = 150;
const circular = (raw: number) => ((raw + count / 2) % count + count) % count - count / 2;
const normal = (value: number) => ((Math.round(value) % count) + count) % count;
function Blade({ index, progress, select }: { index: number; progress: ReturnType<typeof useMotionValue<number>>; select: (i: number) => void }) {
  const offset = useTransform(progress, p => circular(index - p)); const angle = useTransform(offset, o => o * step);
  const x = useTransform(angle, a => Math.sin(a) * radiusX); const z = useTransform(angle, a => Math.cos(a) * radiusZ - radiusZ); const y = useTransform(angle, a => (1 - Math.cos(a)) * verticalDrop);
  const highlight = useTransform(angle, a => `${Math.round(50 + Math.max(-35, Math.min(35, a / (step * 3.2) * 35)))}%`);
  return <motion.button className="lab-crystal-blade" type="button" onClick={() => select(index)} style={{ x, y, z, rotateY: useTransform(angle, a => -a * 57.3), rotateZ: useTransform(angle, a => Math.sin(a) * 3), scale: useTransform(offset, o => Math.max(.48, 1 - Math.abs(o) * .1)), opacity: useTransform(offset, o => Math.max(.1, 1 - Math.abs(o) * .16)), filter: useTransform(offset, o => `brightness(${Math.max(.45, 1.18 - Math.abs(o) * .12)}) saturate(${Math.max(.4, 1.25 - Math.abs(o) * .12)}) blur(${Math.max(0, Math.abs(o)-2)*.7}px)`), zIndex: useTransform(offset, o => 100 - Math.round(Math.abs(o) * 10)), "--highlight-x": highlight } as never}><i className="lab-crystal-refraction" /><i className="lab-crystal-glare" /><i className="lab-crystal-edge" /><i className="lab-crystal-thickness" /><span>0{index + 1}</span><b>{tracks[index]}</b><small>CRYSTAL TEST TRACK</small></motion.button>;
}
export default function CrystalTrackWheelLab() {
  const progress = useMotionValue(0); const [active, setActive] = useState(0); const samples = useRef<{ x:number; p:number; t:number }[]>([]); const wheelTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined); const reduced = typeof window !== "undefined" && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const go = (target: number, velocity = 0) => { const delta = Math.round(target - progress.get()); const shortest = delta > count / 2 ? target - count : delta < -count / 2 ? target + count : target; setActive(normal(shortest)); animate(progress, shortest, reduced ? { duration:.16, ease:"easeOut" } : { type:"spring", stiffness:185, damping:20, mass:.78, velocity }); };
  const settle = (velocity: number) => { const projected = progress.get() + velocity * .28; const snapped = Math.round(projected); if (reduced) go(snapped); else animate(progress, snapped, { type:"inertia", velocity, power:.42, timeConstant:310, modifyTarget: () => snapped, bounceStiffness:220, bounceDamping:19 }); setActive(normal(snapped)); };
  useMotionValueEvent(progress, "change", p => setActive(normal(p)));
  useEffect(() => { const key = (e: KeyboardEvent) => { if (e.key === "ArrowLeft") go(Math.round(progress.get()) - 1); if (e.key === "ArrowRight") go(Math.round(progress.get()) + 1); if ((e.key === "Enter" || e.key === " ") && document.activeElement?.closest(".lab-wheel")) e.preventDefault(); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, []);
  return <section className="crystal-wheel-lab"><p className="section-kicker">MOTION LAB // NO STORE · NO AUDIO</p><h1>Crystal Track Wheel</h1><p className="lab-readout">{String(active + 1).padStart(2,"0")} / {count} · {tracks[active]}</p><div className="lab-wheel" tabIndex={0} onPointerDown={e => { samples.current=[{x:e.clientX,p:progress.get(),t:performance.now()}]; e.currentTarget.setPointerCapture(e.pointerId); }} onPointerMove={e => { if (!e.currentTarget.hasPointerCapture(e.pointerId)) return; const start=samples.current[0]; const p=start.p-(e.clientX-start.x)/pixelsPerItem; progress.set(p); samples.current.push({x:e.clientX,p,t:performance.now()}); if(samples.current.length>5) samples.current.shift(); }} onPointerUp={e => { const a=samples.current[0], b=samples.current.at(-1); settle(a&&b?(b.p-a.p)/Math.max(1,b.t-a.t)*1000:0); e.currentTarget.releasePointerCapture(e.pointerId); }} onWheel={e => { e.preventDefault(); progress.set(progress.get()+e.deltaY/360); clearTimeout(wheelTimer.current); wheelTimer.current=setTimeout(() => settle(-e.deltaY/180),100); }}><div className="lab-wheel-stage">{tracks.map((_, index) => <Blade key={index} index={index} progress={progress} select={go} />)}</div></div><div className="lab-controls"><button onClick={() => go(Math.round(progress.get())-1)} aria-label="Previous experimental track">←</button><button onClick={() => go(Math.round(progress.get())+1)} aria-label="Next experimental track">→</button></div><p className="lab-spec">angle step {step.toFixed(3)} · radius {radiusX}/{radiusZ} · drag {pixelsPerItem}px/item · inertia 0.42/310ms · spring 185/20/.78</p></section>;
}
